services:
  - type: web
    name: background-remover-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: background-remover-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://yashnaiduu.github.io/background-remover-pro
    
databases:
  - name: background-remover-db
    databaseName: background_remover
    user: background_remover_user
